/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dakidev.image_upload.swing;

import com.dakidev.MATCHING_TYPE;
import com.dakidev.image_upload.swing_worker.ImagesUploaderWorker;

import java.awt.Color;

import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.plaf.ColorUIResource;

/**
 * @author anonyme
 */
public class NewJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        ((DefaultEditor) imageColIndexSpinner.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) matchingColIndexSpinner.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) headerRowIndexSpinner.getEditor()).getTextField().setEditable(false);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        selectedProductsFileLabel = new javax.swing.JLabel();
        selectedimagesFolderLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        imageColIndexSpinner = new javax.swing.JSpinner();
        imageColIndexLabel = new javax.swing.JLabel();
        chooseProductsFileButton = new javax.swing.JButton();
        chooseImagesFolderButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        jProgressBar = new javax.swing.JProgressBar();
        matchingColIndexLabel = new javax.swing.JLabel();
        matchingColIndexSpinner = new javax.swing.JSpinner();
        matchingMethodLabel = new javax.swing.JLabel();
        matchingMethodComboBox = new javax.swing.JComboBox<>();
        imagesSeparatorLabel = new javax.swing.JLabel();
        imagesSeparatorTextField = new javax.swing.JTextField();
        extensionsLabel = new javax.swing.JLabel();
        extensionsTextField = new javax.swing.JTextField();
        headerRowIndexLabel = new javax.swing.JLabel();
        headerRowIndexSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app-zid.png"))); // NOI18N

        selectedProductsFileLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        selectedProductsFileLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 97, 163), 1, true));

        selectedimagesFolderLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        selectedimagesFolderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 97, 163), 1, true));

        convertButton.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        convertButton.setText("Load Images");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        imageColIndexSpinner.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        imageColIndexSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        imageColIndexLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        imageColIndexLabel.setText("Images column");
        imageColIndexLabel.setPreferredSize(new java.awt.Dimension(76, 47));

        chooseProductsFileButton.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        chooseProductsFileButton.setText("Product file");
        chooseProductsFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseProductFileActionPerformed(evt);
            }
        });

        chooseImagesFolderButton.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        chooseImagesFolderButton.setText("Images folder");
        chooseImagesFolderButton.setMaximumSize(new java.awt.Dimension(172, 36));
        chooseImagesFolderButton.setMinimumSize(new java.awt.Dimension(172, 36));
        chooseImagesFolderButton.setPreferredSize(new java.awt.Dimension(172, 36));
        chooseImagesFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImagesFolderActionPerformed(evt);
            }
        });

        consoleTextArea.setColumns(20);
        consoleTextArea.setForeground(java.awt.Color.red);
        consoleTextArea.setRows(5);
        jScrollPane.setViewportView(consoleTextArea);

        jProgressBar.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(253, 206, 74));
        jProgressBar.setStringPainted(true);

        matchingColIndexLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        matchingColIndexLabel.setText("Matching column");
        matchingColIndexLabel.setPreferredSize(new java.awt.Dimension(76, 47));

        matchingColIndexSpinner.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        matchingColIndexSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        matchingMethodLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        matchingMethodLabel.setText("Matching method");
        matchingMethodLabel.setPreferredSize(new java.awt.Dimension(76, 47));

        matchingMethodComboBox.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        matchingMethodComboBox.setModel(new DefaultComboBoxModel<>(MATCHING_TYPE.values()));

        imagesSeparatorLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        imagesSeparatorLabel.setText("Images Separator ");
        imagesSeparatorLabel.setPreferredSize(new java.awt.Dimension(76, 47));

        imagesSeparatorTextField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        imagesSeparatorTextField.setText(",");

        extensionsLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        extensionsLabel.setText("extensions( \",\" separator)");
        extensionsLabel.setPreferredSize(new java.awt.Dimension(76, 47));

        extensionsTextField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        headerRowIndexLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        headerRowIndexLabel.setText("Header row");
        headerRowIndexLabel.setPreferredSize(new java.awt.Dimension(76, 47));

        headerRowIndexSpinner.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        headerRowIndexSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(chooseImagesFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chooseProductsFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matchingMethodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(54, 54, 54)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matchingMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(selectedimagesFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                                        .addComponent(selectedProductsFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(extensionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(extensionsTextField)
                                .addGap(310, 310, 310))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(headerRowIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerRowIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imageColIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imageColIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matchingColIndexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(matchingColIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(426, 426, 426)))
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(imagesSeparatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagesSeparatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(97, 97, 97)))
                        .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseProductsFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectedProductsFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseImagesFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectedimagesFolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(headerRowIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerRowIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageColIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imageColIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(matchingColIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matchingColIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matchingMethodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matchingMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extensionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extensionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagesSeparatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagesSeparatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        
        consoleTextArea.setText("");
        
        MATCHING_TYPE selectedMatchingMethod = (MATCHING_TYPE) matchingMethodComboBox.getSelectedItem();
        
        StringBuilder errorMessageBuilder = new StringBuilder();
        
        if (selectedProductsFileLabel.getText().equals(""))
            errorMessageBuilder.append("Please choose products file").append("\n");
        
        if ((selectedMatchingMethod == MATCHING_TYPE.FOLDER || selectedMatchingMethod == MATCHING_TYPE.FOLDER_WITH_EXTENSIONS) && selectedimagesFolderLabel.getText().equals(""))
            errorMessageBuilder.append("Please choose images folder").append("\n");
        
        if (selectedMatchingMethod == MATCHING_TYPE.FOLDER_WITH_EXTENSIONS && extensionsTextField.getText().trim().isEmpty())
            errorMessageBuilder.append("Please provide images suffix").append("\n");
    
        if ((selectedMatchingMethod == MATCHING_TYPE.FOLDER || selectedMatchingMethod == MATCHING_TYPE.FOLDER_WITH_EXTENSIONS) && imagesSeparatorTextField.getText().equals(""))
            errorMessageBuilder.append("Please provide images separator").append("\n");
        
        if (!errorMessageBuilder.toString().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, errorMessageBuilder.toString(), "", JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        new ImagesUploaderWorker(jProgressBar, consoleTextArea, (Integer) imageColIndexSpinner.getValue() - 1, (Integer) matchingColIndexSpinner.getValue() - 1,
                (Integer) headerRowIndexSpinner.getValue() - 1, selectedMatchingMethod, extensionsTextField.getText().trim(), selectedProductsFileLabel.getText().trim(),
                selectedimagesFolderLabel.getText().trim(),
                imagesSeparatorTextField.getText().trim()).execute();
        
    }//GEN-LAST:event_convertButtonActionPerformed
    
    private void chooseProductFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseProductFileActionPerformed
        
        JFileChooser jFileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jFileChooser.setPreferredSize(new Dimension(800, 500));
        
        jFileChooser.setAcceptAllFileFilterUsed(false);
        
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("Only .xlsx files", "xlsx");
        jFileChooser.addChoosableFileFilter(restrict);
        
        int r = jFileChooser.showOpenDialog(null);
        
        if (r == JFileChooser.APPROVE_OPTION) {
            selectedProductsFileLabel.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            
        } else {
            selectedProductsFileLabel.setText("");
        }
    }//GEN-LAST:event_chooseProductFileActionPerformed
    
    private void chooseImagesFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImagesFolderActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jFileChooser.setPreferredSize(new Dimension(800, 500));
        
        jFileChooser.setAcceptAllFileFilterUsed(false);
    
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int r = jFileChooser.showOpenDialog(null);
        
        if (r == JFileChooser.APPROVE_OPTION) {
            selectedimagesFolderLabel.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            
        } else {
            selectedimagesFolderLabel.setText("");
        }
    }//GEN-LAST:event_chooseImagesFolderActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        UIManager.put("textForeground", new ColorUIResource(34, 97, 163));
        UIManager.getLookAndFeelDefaults().put("nimbusOrange", new Color(34, 97, 163));
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseImagesFolderButton;
    private javax.swing.JButton chooseProductsFileButton;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.JButton convertButton;
    private javax.swing.JLabel extensionsLabel;
    private javax.swing.JTextField extensionsTextField;
    private javax.swing.JLabel headerRowIndexLabel;
    private javax.swing.JSpinner headerRowIndexSpinner;
    private javax.swing.JLabel imageColIndexLabel;
    private javax.swing.JSpinner imageColIndexSpinner;
    private javax.swing.JLabel imagesSeparatorLabel;
    private javax.swing.JTextField imagesSeparatorTextField;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel matchingColIndexLabel;
    private javax.swing.JSpinner matchingColIndexSpinner;
    private javax.swing.JComboBox<MATCHING_TYPE> matchingMethodComboBox;
    private javax.swing.JLabel matchingMethodLabel;
    private javax.swing.JLabel selectedProductsFileLabel;
    private javax.swing.JLabel selectedimagesFolderLabel;
    // End of variables declaration//GEN-END:variables
}
